#!/bin/bash
# run_hw_emu.sh -- ONE-COMMAND hw_emu gate of 3 x 8x4 (broadcast vector) (step 3 of BUILD.md).
# GENERATED by multi_tenant/make_bcast_build.py.
#
#   tmux new -d -s 8x4_x3_bcast_emu 'bash ~/GEMV_Sparse/Vitis_multi_8x4_x3_bcast/run_hw_emu.sh'
#
# Links the hw_emu bitstream (unless it exists), builds host_workload_bcast, and runs the MoE
# correctness gate against it: every engine must be bit-exact on all 3 layers, computing from
# the ONE vector the broadcast pair sends. Uses a PRIVATE copy of the Emulation scripts
# (emu_hw_emu/), so it never touches the shared Emulation directory and can run beside a
# hardware link or a card run. Everything goes to hw_emu_gate.log; the tmux window stays open.
#
# NOTHING TYPED IN THE WINDOW CAN KILL THE RUN (2026-09-29: the first x3_bcast gate died
# silently mid-simulation when its window closed, most likely from a Ctrl-C on attach -- it
# reached every process there, the log writer too). So: Ctrl-C, Ctrl-\ and hang-up are ignored
# by this script and by everything it starts (an ignored signal is inherited), the gate runs in
# a session of its own when setsid can wait for it, reads nothing from the terminal, and its
# progress reaches the log line by line (PYTHONUNBUFFERED). WATCH IT WITH
#     tail -f hw_emu_gate.log          (Ctrl-C there stops only tail)
# STOP IT, if ever needed, with
#     pkill -u $USER -f "run_workload_bcast.py --arch 3x8x4_bcast"; pkill -u $USER -f host_workload_bcast

trap '' INT QUIT HUP
cd "$(dirname "$0")" || exit 1
exec 3>&1 4>&2                         # the terminal, given back to the shell left open at the end
source /opt/Xilinx/Vitis/2021.1/settings64.sh
source /opt/xilinx/xrt/setup.sh
export PLATFORM=/opt/xilinx/platforms/xilinx_u280_xdma_201920_3/xilinx_u280_xdma_201920_3.xpfm
EMU_XCLBIN=sparse_8x4_x3_bcast.hw_emu.xclbin
TOOLS=$HOME/GEMV_Sparse/workload_tools
EMU_SRC=$HOME/GEMV_Sparse/GEMV_4.0_Source/Emulation

# the window's shell: the terminal back, Ctrl-C working again
end_shell() { exec 1>&3 2>&4 3>&- 4>&-; trap - INT QUIT HUP; exec bash; }
fail() { echo "STOPPED: $*"; end_shell; }
exec > >(tee -a hw_emu_gate.log) 2>&1

[ -f "$PLATFORM" ] || fail "platform file missing: $PLATFORM"
for f in ../krnl_gemv_sparse_8x4.xo krnl_mm2s.hw_emu.xo krnl_s2mm.hw_emu.xo krnl_mm2s_bcast3.hw_emu.xo \
         sparse_hbm_8x4_x3_bcast.cfg "$TOOLS/run_workload_bcast.py" "$TOOLS/plan_workload_bcast.py" \
         "$TOOLS/host_workload_bcast.cpp" "$EMU_SRC/gemv4_cosim_gen.py"; do
    [ -f "$f" ] || fail "missing $f"
done
if pgrep -u "$USER" -f -- "-o $EMU_XCLBIN" >/dev/null; then
    fail "the hw_emu link of this build is already running (see: tmux ls)"
fi
if pgrep -u "$USER" -f -- "run_workload_bcast.py --arch 3x8x4_bcast " >/dev/null; then
    fail "a gate of this build is already running (it survives its window closing) -- see the pkill line at the top of this script"
fi

echo "=== hw_emu gate of 3 x 8x4 (broadcast vector) -- started $(date)"
if [ ! -f "$EMU_XCLBIN" ]; then
    echo "--- linking $EMU_XCLBIN"
    v++ -t hw_emu --platform "$PLATFORM" --config sparse_hbm_8x4_x3_bcast.cfg \
        --kernel_frequency 375 -l -o "$EMU_XCLBIN" --temp_dir _x_hw_emu \
        ../krnl_gemv_sparse_8x4.xo krnl_mm2s.hw_emu.xo krnl_s2mm.hw_emu.xo krnl_mm2s_bcast3.hw_emu.xo \
        || fail "the hw_emu link failed (see above)"
    echo "--- linked $(date)"
else
    echo "--- $EMU_XCLBIN exists, not relinked"
fi
emconfigutil --platform "$PLATFORM" --nd 1 >/dev/null || fail "emconfigutil failed"
cp "$TOOLS/host_workload_bcast.cpp" . || fail "cannot copy the host"
g++ -Wall -O2 -std=c++1y -I"$XILINX_XRT/include" host_workload_bcast.cpp -L"$XILINX_XRT/lib" \
    -lOpenCL -lrt -lstdc++ -pthread -DCORES=8 -DBLOCKS=4 -o host_workload_bcast \
    || fail "host_workload_bcast did not compile"
rm -rf emu_hw_emu && mkdir -p emu_hw_emu && cp "$EMU_SRC"/*.py emu_hw_emu/ \
    || fail "cannot copy the Emulation scripts"
export XCL_EMULATION_MODE=hw_emu
export PYTHONUNBUFFERED=1              # the gate's progress reaches the log as it happens
DETACH=""                              # a session of its own, when setsid can wait for it
setsid -w true </dev/null >/dev/null 2>&1 && DETACH="setsid -w"
echo "--- MoE gate on the emulated card $(date)${DETACH:+ (own session)}"
$DETACH python3 "$TOOLS/run_workload_bcast.py" --arch 3x8x4_bcast --correctness --emu emu_hw_emu \
    --xclbin "$EMU_XCLBIN" --clock 375 --host-timeout 14400 < /dev/null
rc=$?
unset XCL_EMULATION_MODE
echo
if [ $rc -eq 0 ]; then
    echo "=== hw_emu GATE PASSED $(date) -- start the hardware link:"
    echo "    tmux new -d -s 8x4_x3_bcast 'bash ~/GEMV_Sparse/Vitis_multi_8x4_x3_bcast/start_build.sh'"
else
    echo "=== hw_emu GATE FAILED (exit $rc) $(date) -- do NOT start the hardware link"
fi
end_shell
