"""Merge the per-configuration shape sweeps into results/GEMV_shapes_<clock>MHz.csv.

run_shapes.py writes ONE CSV PER CONFIGURATION (shapes_dense_*.csv,
shapes_00_*.csv ... shapes_mix_*.csv), each with 21 columns and no knowledge of
the other configurations. Everything comparative -- speed-up against dense,
normalised latency, % of theory -- can only be computed once all six are in
hand. That is what this script does, and it is why the merged file has 24
columns rather than 21.

The 300 MHz merge was originally done ad hoc, with no script kept. This
reproduces it exactly and then does the same for 325, so both clocks are
generated by identical code rather than one being hand-made.

  VALIDATE BEFORE YOU TRUST IT:

      python make_shapes_csv.py --clock 300 --out /tmp/check.csv

  then diff against results/GEMV_shapes_300MHz.csv. If the script cannot
  reproduce the file that the existing charts are built on, it is wrong, and
  the 325 output it produces would be wrong in the same way.

COLUMN ORDER IS LOAD-BEARING. GEMV_Charts_Final.xlsx addresses the Shapes sheet
by ABSOLUTE cell reference (Shapes!S14 and so on). Inserting a column silently
re-points every series one column over -- no error, no visual tell, a chart that
plots bandwidth where it claims speed-up. `data_source` stays LAST. Append only,
never insert.

WHAT THE GEOMEAN ROW IS. shape_order 12, one per configuration: the geometric
mean over the 11 shapes of dsp_occupancy, GFLOPS_effective, speedup_vs_dense and
latency_norm_dense. Geometric, not arithmetic, because these are RATIOS -- the
mean of a speed-up and its reciprocal must be 1, which only the geometric mean
gives. Size-dependent columns (latency, dimensions, beats) are left BLANK on
that row: a geomean of latencies across a 864x size range is not a quantity.

Run:  python make_shapes_csv.py --clock 325
"""

import argparse
import csv
import io
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "results")

# (candidate filename suffixes, label, sparsity_order, theory speed-up)
#
# TWO NAMING CONVENTIONS EXIST and both are on disk. The 300 MHz sweep was run
# with descriptive names (shapes_2to4_300MHz.csv); the 325 MHz sweep was run from
# a shell loop over the sparsity CODES, giving shapes_00_325MHz.csv. Neither is
# wrong, so this accepts either rather than renaming measured data -- a rename
# would break the provenance of files already cited in the workbook.
#
# MIXED's theory is NOT a guess: the four equal-row quarters run at freeze
# 8/4/2/1, so the matrix costs (8+4+2+1)/4 = 3.75 beats per 2 rows = 1.875
# beats/row against dense's 8 -- exactly 8/1.875 = 4.2667x. The original 300 MHz
# merge left this cell blank; filling it is a correction, not a change of method.
CONFIGS = [
    (["dense"],          "dense", 1, None),
    (["00", "2to4"],     "2:4",   2, 2.0),
    (["01", "2to8"],     "2:8",   3, 4.0),
    (["10", "2to16"],    "2:16",  4, 8.0),
    (["11", "2to32"],    "2:32",  5, 16.0),
    (["mix", "mixed"],   "MIXED", 6, 8.0 / 1.875),
]

SHAPE_ORDER = ["G1", "G2", "G3", "G4", "G5", "G6", "G7", "G8", "G9", "G10", "G11"]

COLS = ["design", "sparsity", "shape", "dimensions", "matrix_elements",
        "shape_order", "sparsity_order", "M_rows", "N_cols", "nwin",
        "beats_per_matrix", "batch_R", "latency_per_matrix_us",
        "ideal_per_matrix_us", "dsp_occupancy", "GFLOPS_effective",
        "GFLOPS_actual", "bandwidth_GBs", "speedup_vs_dense",
        "latency_norm_dense", "theory_speedup", "pct_of_theory",
        "spread_pct", "data_source"]

GEO_COLS = ["dsp_occupancy", "GFLOPS_effective", "speedup_vs_dense",
            "latency_norm_dense"]


def geomean(vals):
    p = 1.0
    for v in vals:
        p *= v
    return p ** (1.0 / len(vals))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--clock", type=int, required=True, help="300 or 325")
    ap.add_argument("--out", default=None, help="override output path")
    a = ap.parse_args()

    src = {}
    for suffixes, label, _order, _th in CONFIGS:
        cand = [os.path.join(DATA, "shapes_%s_%dMHz.csv" % (s, a.clock))
                for s in suffixes]
        found = [c for c in cand if os.path.exists(c)]
        if not found:
            raise SystemExit("MISSING for %s -- tried:\n  %s"
                             % (label, "\n  ".join(cand)))
        p = found[0]
        rows = {}
        for r in csv.DictReader(io.open(p, newline="", encoding="utf-8")):
            rows[r["shape"]] = r
        missing = [s for s in SHAPE_ORDER if s not in rows]
        if missing:
            raise SystemExit("%s is missing shapes: %s" % (p, ", ".join(missing)))
        src[label] = rows

    dense = src["dense"]
    out = []
    for _suffixes, label, order, theory in CONFIGS:
        rows = src[label]
        acc = {c: [] for c in GEO_COLS}
        for si, shape in enumerate(SHAPE_ORDER, start=1):
            r = rows[shape]
            lat = float(r["latency_per_matrix_us"])
            dlat = float(dense[shape]["latency_per_matrix_us"])
            speedup = dlat / lat
            norm = lat / dlat
            occ = float(r["dsp_occupancy"])
            gfe = float(r["GFLOPS_effective"])
            M, N = int(r["M_rows"]), int(r["N_cols"])

            rec = dict(
                design=r["design"], sparsity=label, shape=shape,
                dimensions="%dx%d" % (M, N), matrix_elements=M * N,
                shape_order=si, sparsity_order=order,
                M_rows=M, N_cols=N, nwin=int(r["nwin"]),
                beats_per_matrix=int(r["beats_per_matrix"]),
                batch_R=int(r["batch_R"]),
                latency_per_matrix_us=round(lat, 4),
                ideal_per_matrix_us=round(float(r["ideal_per_matrix_us"]), 4),
                dsp_occupancy=round(occ, 4),
                GFLOPS_effective=gfe,
                GFLOPS_actual=float(r["GFLOPS_actual"]),
                bandwidth_GBs=float(r["bandwidth_GBs"]),
                speedup_vs_dense=round(speedup, 4),
                latency_norm_dense=round(norm, 4),
                theory_speedup=(theory if theory is not None else ""),
                pct_of_theory=(round(100.0 * speedup / theory, 2)
                               if theory is not None else ""),
                spread_pct=float(r["spread_pct"]),
                data_source="measured")
            out.append(rec)
            for c, v in (("dsp_occupancy", occ), ("GFLOPS_effective", gfe),
                         ("speedup_vs_dense", speedup),
                         ("latency_norm_dense", norm)):
                acc[c].append(v)

        g = {c: geomean(acc[c]) for c in GEO_COLS}
        gspeed = g["speedup_vs_dense"]
        out.append(dict(
            design=rows[SHAPE_ORDER[0]]["design"], sparsity=label,
            shape="GEOMEAN", dimensions="", matrix_elements="",
            shape_order=12, sparsity_order=order,
            M_rows="", N_cols="", nwin="", beats_per_matrix="", batch_R="",
            latency_per_matrix_us="", ideal_per_matrix_us="",
            dsp_occupancy=round(g["dsp_occupancy"], 4),
            GFLOPS_effective=round(g["GFLOPS_effective"], 2),
            GFLOPS_actual="", bandwidth_GBs="",
            speedup_vs_dense=round(gspeed, 4),
            latency_norm_dense=round(g["latency_norm_dense"], 4),
            theory_speedup=(theory if theory is not None else ""),
            pct_of_theory=(round(100.0 * gspeed / theory, 2)
                           if theory is not None else ""),
            spread_pct="", data_source="measured"))

    path = a.out or os.path.join(DATA, "GEMV_shapes_%dMHz.csv" % a.clock)
    d = os.path.dirname(path)
    if d and not os.path.isdir(d):
        os.makedirs(d)
    with io.open(path, "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=COLS, lineterminator="\r\n")
        w.writeheader()
        for r in out:
            w.writerow(r)
    print("wrote %s : %d rows x %d cols" % (path, len(out), len(COLS)))

    print("\n  GEOMEAN over 11 shapes @ %d MHz" % a.clock)
    print("  %-7s %10s %10s %9s %9s" %
          ("config", "speedup", "theory", "%theory", "GF_eff"))
    for r in out:
        if r["shape"] != "GEOMEAN":
            continue
        print("  %-7s %10.4f %10s %9s %9.2f" %
              (r["sparsity"], r["speedup_vs_dense"],
               ("%.4f" % r["theory_speedup"]) if r["theory_speedup"] != "" else "--",
               ("%.2f%%" % r["pct_of_theory"]) if r["pct_of_theory"] != "" else "--",
               r["GFLOPS_effective"]))


if __name__ == "__main__":
    main()
