#!/bin/bash
# start_build.sh -- ONE-COMMAND hardware link of 2 x 16x3 (broadcast vector), target 375 MHz.
# GENERATED by multi_tenant/make_bcast_build.py.
#
#   tmux new -d -s 16x3_x2_bcast 'bash ~/GEMV_Sparse/Vitis_multi_16x3_x2_bcast/start_build.sh'
#
# Checks everything first and refuses to start if anything is wrong (the reason is
# printed and the tmux window stays open: tmux attach -t 16x3_x2_bcast). SEVERAL builds may run
# side by side: it refuses only if THIS build is already running, or if the server is
# short of memory or disk. 30 minutes in it writes check_30min.txt: stream warnings must
# be 0 and the synthesis line must contain AlternateRoutability. At the end it prints
# the DATA_CLK the card will run at and copies the reports to
# ~/GEMV_Sparse/reports_multi_16x3_x2_bcast/.

cd "$(dirname "$0")" || exit 1
source /opt/Xilinx/Vitis/2021.1/settings64.sh
source /opt/xilinx/xrt/setup.sh
export PLATFORM=/opt/xilinx/platforms/xilinx_u280_xdma_201920_3/xilinx_u280_xdma_201920_3.xpfm
export BDF=0000:af:00.1
XCLBIN=sparse_16x3_x2_bcast_375.xclbin

fail() { echo "NOT STARTED: $*"; exec bash; }

[ -f "$PLATFORM" ] || fail "platform file missing: $PLATFORM"
for f in ../krnl_gemv_sparse_16x3.xo krnl_mm2s.hw.xo krnl_s2mm.hw.xo krnl_mm2s_bcast2.hw.xo \
         impl_family.cfg sparse_hbm_16x3_x2_bcast.cfg slr_floorplan_16x3_x2_bcast_split.cfg; do
    [ -f "$f" ] || fail "missing $f in $(pwd)"
done
if pgrep -u "$USER" -f -- "-o $XCLBIN" >/dev/null; then
    fail "this build ($XCLBIN) is already running (see: tmux ls)"
fi
[ -e "$XCLBIN" ] && fail "$XCLBIN already exists -- already built"
grep -q "GATE PASSED" hw_emu_gate.log 2>/dev/null \
    || echo "NOTE: no passed hw_emu gate in hw_emu_gate.log (BUILD.md step 3) -- linking anyway"
free_gb=$(df -BG --output=avail ~ | tail -1 | tr -dc 0-9)
[ "${free_gb:-0}" -ge 40 ] || fail "only ${free_gb} GB free in /home -- a full disk kills a link"
mem_gb=$(free -g | awk '/^Mem:/ {print $7}')
[ "${mem_gb:-0}" -ge 24 ] || fail "only ${mem_gb} GB of RAM available -- a link peaks near 20 GB"

( sleep 1800
  { echo "checked $(date)"
    echo "stream/connect warnings from v++ (must be 0): $(grep -ciE 'warning.*(stream|connect)' link_hw_16x3_x2_bcast.log 2>/dev/null)"
    echo "critical warnings / errors from v++ (must be 0): $(grep -cE '^(CRITICAL WARNING|ERROR)' link_hw_16x3_x2_bcast.log 2>/dev/null)"
    echo "synthesis of the dynamic region (must contain AlternateRoutability; empty = not started yet):"
    grep -rhoE --include='*.log' 'synth_design -top pfm_dynamic -part[^"]*' _x/link 2>/dev/null | sort -u | head -2
  } > check_30min.txt ) < /dev/null &

echo "linking 2 x 16x3 (broadcast vector) at 375 MHz -- started $(date), ${free_gb} GB disk, ${mem_gb} GB RAM free"
v++ -t hw --platform "$PLATFORM" --config sparse_hbm_16x3_x2_bcast.cfg --config impl_family.cfg \
    --config slr_floorplan_16x3_x2_bcast_split.cfg --kernel_frequency 375 -l -o "$XCLBIN" \
    ../krnl_gemv_sparse_16x3.xo krnl_mm2s.hw.xo krnl_s2mm.hw.xo krnl_mm2s_bcast2.hw.xo 2>&1 \
    | tee link_hw_16x3_x2_bcast.log
echo "v++ finished $(date)."
if [ -f "$XCLBIN" ]; then
    echo "DATA_CLK (the clock the card runs this bitstream at):"
    xclbinutil --info --input "$XCLBIN" | grep -A2 DATA_CLK
    RS=$(ls _x/reports/link/imp/impl_1_*_timing_summary_postroute_physopted.rpt 2>/dev/null | head -1)
    [ -n "$RS" ] && awk '/Intra Clock Table/,/Inter Clock Table/' "$RS" \
        | awk 'NF>5 {print $1, $2, $4}' | grep -E 'kernel_0|hbm_aclk_0'
    mkdir -p ~/GEMV_Sparse/reports_multi_16x3_x2_bcast && cp -r _x/reports/link/imp ~/GEMV_Sparse/reports_multi_16x3_x2_bcast/
    echo "reports copied to ~/GEMV_Sparse/reports_multi_16x3_x2_bcast/"
else
    echo "NO XCLBIN -- the link failed; the reason is near the end of link_hw_16x3_x2_bcast.log"
fi
exec bash
