// GENERATED by make_family_build.py for 4x32 (4 cores x 32 blocks).
//
// host_sparse.cpp already carries these as `static const int` at its top --
// it was written parameterised, so NOTHING ELSE in it needs to change. Either
// #include this file and delete those six lines, or just retype the six values.
//
// LANES is the one that is easy to get wrong: it is CORES x BLOCKS, and it
// divides the output-beat count. Wrong LANES = wrong throughput arithmetic in
// the summary, with correct hardware -- a silent reporting error.

static const int PC_BYTES  = 32;   // 256-bit pseudo-channel beat
static const int W_PCS     = 16;
static const int IND_PCS   = 6;
static const int A_PCS     = 2;
static const int C_PCS     = 8;
static const int LANES     = 128;   // 4 cores x 32 blocks
static const int WIN_ELEMS = 32;   // activation elements per window

// Where the 2-bit sparsity code sits. Derived, not hardcoded, so every other
// configuration is a constants change and nothing else -- see the note below.
static const int IND_BITS  = 1280;   // 10 x LANES, index bits in the joined word
static const int SP_PC     = IND_BITS / 256;         // = 5, which index PC
static const int SP_BYTE   = (IND_BITS % 256) / 8;   // = 0, byte within it

// ---- AND ONE THING THAT IS *NOT* A CONSTANT IN host_sparse.cpp ------------
//
// lap_sparsity() reads the 2-bit code back out of the index image with a
// HARDCODED offset:
//
//     return (unsigned)(ind_pc2.p[k * PC_BYTES + 16] & 0x3);   // <- 8x8 ONLY
//
// That offset is 8x8-specific. The code rides at bit IND_BITS of the JOINED
// index word, so both which PC holds it and the byte within that PC move with
// the configuration. For 4x32 (IND_BITS = 1280) it is:
//
//     return (unsigned)(ind_pc5.p[k * PC_BYTES + 0] & 0x3);
//
// i.e. index PC 5, byte 0.  NOTE: PC 5 holds NOTHING BUT these two bits --
// the 1280 index bits fill PC0..4 exactly.
//
// Get this wrong and the host reads a WRONG SPARSITY MODE off correct
// hardware: the run completes, the numbers look plausible, and the reported
// mode is a lie. Nothing errors.
//
// PATCH IT ONCE, DERIVED, AND NO CONFIG EVER NEEDS IT AGAIN. Three edits:
//
//   sparsity_at()  p[k * PC_BYTES + 16]  ->  p[k * PC_BYTES + SP_BYTE]
//   both callers   sparsity_at(i_img[2], ...) -> sparsity_at(i_img[SP_PC], ...)
//
// After that the file is fully parameterised and every remaining config is a
// constants change only.

// For the Python packer (hex_to_bin.py / gen_timing_stimulus.py):
//   W_PCS=16  IND_PCS=6  A_PCS=2  C_PCS=8
//   CORES=4  BLOCKS=32  LANES=128  SPARSITY_BIT=1280  (bit of the joined word)
