// ---------------------------------------------------------------------------
// krnl_gemv_sparse.v -- Vitis RTL kernel top for the 2:M SPARSE GEMV engine.
//
// GENERATED by make_family_build.py for the 4x32 configuration
// (4 cores x 32 blocks = 128 blocks, 1024 DSPs, 32 AXI4-Stream ports).
//
// This is the RTL Kernel Wizard's generated top with ONE change, exactly where
// the generated comments invite it: the placeholder example instance is
// replaced by two2N_axis (the AXIS splitter around the verified two2N).
// The module name, parameters and ports follow the wizard's conventions --
// package_xo infers the 32 AXI4-Stream interfaces from them.
//
// INDEX TLAST. two2N has no index tlast port and needs none: weight TLAST is
// the end-of-calculation marker and activation TLAST the end-of-vector one.
// The AXIS rules still require the signal on the interface, and krnl_mm2s
// drives it, so the wrapper accepts all 6 and leaves them unconnected.
//
// SPARSITY is NOT a port. The 2-bit code rides in the LAST index PC's padding,
// bits [1281:1280] of the joined 1536-bit index word. It is buffer CONTENT written
// by the host packer, invisible to this kernel and to every data mover.
//
// Mixed-language: this Verilog top instantiates a VHDL entity. Vivado resolves
// that by entity name; two2N_axis's generics are DEFAULTED to this config's
// values, because no generic mapping is possible from Verilog.
// ---------------------------------------------------------------------------

`default_nettype none
`timescale 1 ns / 1 ps
// Top level of the kernel. Do not modify module name, parameters or ports.
module krnl_gemv_sparse #(
  parameter integer C_S_AXIS_W0_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_W1_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_W2_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_W3_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_W4_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_W5_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_W6_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_W7_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_W8_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_W9_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_W10_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_W11_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_W12_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_W13_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_W14_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_W15_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_IND0_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_IND1_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_IND2_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_IND3_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_IND4_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_IND5_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_A0_TDATA_WIDTH = 256,
  parameter integer C_S_AXIS_A1_TDATA_WIDTH = 256,
  parameter integer C_M_AXIS_C0_TDATA_WIDTH = 256,
  parameter integer C_M_AXIS_C1_TDATA_WIDTH = 256,
  parameter integer C_M_AXIS_C2_TDATA_WIDTH = 256,
  parameter integer C_M_AXIS_C3_TDATA_WIDTH = 256,
  parameter integer C_M_AXIS_C4_TDATA_WIDTH = 256,
  parameter integer C_M_AXIS_C5_TDATA_WIDTH = 256,
  parameter integer C_M_AXIS_C6_TDATA_WIDTH = 256,
  parameter integer C_M_AXIS_C7_TDATA_WIDTH = 256
)
(
  // System Signals
  input  wire                                  ap_clk          ,
  input  wire                                  ap_rst_n        ,
  // AXI4-Stream (slave) interface s_axis_w0
  input  wire                                  s_axis_w0_tvalid,
  output wire                                  s_axis_w0_tready,
  input  wire [C_S_AXIS_W0_TDATA_WIDTH-1:0]   s_axis_w0_tdata ,
  input  wire [C_S_AXIS_W0_TDATA_WIDTH/8-1:0] s_axis_w0_tkeep ,
  input  wire                                  s_axis_w0_tlast ,
  // AXI4-Stream (slave) interface s_axis_w1
  input  wire                                  s_axis_w1_tvalid,
  output wire                                  s_axis_w1_tready,
  input  wire [C_S_AXIS_W1_TDATA_WIDTH-1:0]   s_axis_w1_tdata ,
  input  wire [C_S_AXIS_W1_TDATA_WIDTH/8-1:0] s_axis_w1_tkeep ,
  input  wire                                  s_axis_w1_tlast ,
  // AXI4-Stream (slave) interface s_axis_w2
  input  wire                                  s_axis_w2_tvalid,
  output wire                                  s_axis_w2_tready,
  input  wire [C_S_AXIS_W2_TDATA_WIDTH-1:0]   s_axis_w2_tdata ,
  input  wire [C_S_AXIS_W2_TDATA_WIDTH/8-1:0] s_axis_w2_tkeep ,
  input  wire                                  s_axis_w2_tlast ,
  // AXI4-Stream (slave) interface s_axis_w3
  input  wire                                  s_axis_w3_tvalid,
  output wire                                  s_axis_w3_tready,
  input  wire [C_S_AXIS_W3_TDATA_WIDTH-1:0]   s_axis_w3_tdata ,
  input  wire [C_S_AXIS_W3_TDATA_WIDTH/8-1:0] s_axis_w3_tkeep ,
  input  wire                                  s_axis_w3_tlast ,
  // AXI4-Stream (slave) interface s_axis_w4
  input  wire                                  s_axis_w4_tvalid,
  output wire                                  s_axis_w4_tready,
  input  wire [C_S_AXIS_W4_TDATA_WIDTH-1:0]   s_axis_w4_tdata ,
  input  wire [C_S_AXIS_W4_TDATA_WIDTH/8-1:0] s_axis_w4_tkeep ,
  input  wire                                  s_axis_w4_tlast ,
  // AXI4-Stream (slave) interface s_axis_w5
  input  wire                                  s_axis_w5_tvalid,
  output wire                                  s_axis_w5_tready,
  input  wire [C_S_AXIS_W5_TDATA_WIDTH-1:0]   s_axis_w5_tdata ,
  input  wire [C_S_AXIS_W5_TDATA_WIDTH/8-1:0] s_axis_w5_tkeep ,
  input  wire                                  s_axis_w5_tlast ,
  // AXI4-Stream (slave) interface s_axis_w6
  input  wire                                  s_axis_w6_tvalid,
  output wire                                  s_axis_w6_tready,
  input  wire [C_S_AXIS_W6_TDATA_WIDTH-1:0]   s_axis_w6_tdata ,
  input  wire [C_S_AXIS_W6_TDATA_WIDTH/8-1:0] s_axis_w6_tkeep ,
  input  wire                                  s_axis_w6_tlast ,
  // AXI4-Stream (slave) interface s_axis_w7
  input  wire                                  s_axis_w7_tvalid,
  output wire                                  s_axis_w7_tready,
  input  wire [C_S_AXIS_W7_TDATA_WIDTH-1:0]   s_axis_w7_tdata ,
  input  wire [C_S_AXIS_W7_TDATA_WIDTH/8-1:0] s_axis_w7_tkeep ,
  input  wire                                  s_axis_w7_tlast ,
  // AXI4-Stream (slave) interface s_axis_w8
  input  wire                                  s_axis_w8_tvalid,
  output wire                                  s_axis_w8_tready,
  input  wire [C_S_AXIS_W8_TDATA_WIDTH-1:0]   s_axis_w8_tdata ,
  input  wire [C_S_AXIS_W8_TDATA_WIDTH/8-1:0] s_axis_w8_tkeep ,
  input  wire                                  s_axis_w8_tlast ,
  // AXI4-Stream (slave) interface s_axis_w9
  input  wire                                  s_axis_w9_tvalid,
  output wire                                  s_axis_w9_tready,
  input  wire [C_S_AXIS_W9_TDATA_WIDTH-1:0]   s_axis_w9_tdata ,
  input  wire [C_S_AXIS_W9_TDATA_WIDTH/8-1:0] s_axis_w9_tkeep ,
  input  wire                                  s_axis_w9_tlast ,
  // AXI4-Stream (slave) interface s_axis_w10
  input  wire                                  s_axis_w10_tvalid,
  output wire                                  s_axis_w10_tready,
  input  wire [C_S_AXIS_W10_TDATA_WIDTH-1:0]   s_axis_w10_tdata ,
  input  wire [C_S_AXIS_W10_TDATA_WIDTH/8-1:0] s_axis_w10_tkeep ,
  input  wire                                  s_axis_w10_tlast ,
  // AXI4-Stream (slave) interface s_axis_w11
  input  wire                                  s_axis_w11_tvalid,
  output wire                                  s_axis_w11_tready,
  input  wire [C_S_AXIS_W11_TDATA_WIDTH-1:0]   s_axis_w11_tdata ,
  input  wire [C_S_AXIS_W11_TDATA_WIDTH/8-1:0] s_axis_w11_tkeep ,
  input  wire                                  s_axis_w11_tlast ,
  // AXI4-Stream (slave) interface s_axis_w12
  input  wire                                  s_axis_w12_tvalid,
  output wire                                  s_axis_w12_tready,
  input  wire [C_S_AXIS_W12_TDATA_WIDTH-1:0]   s_axis_w12_tdata ,
  input  wire [C_S_AXIS_W12_TDATA_WIDTH/8-1:0] s_axis_w12_tkeep ,
  input  wire                                  s_axis_w12_tlast ,
  // AXI4-Stream (slave) interface s_axis_w13
  input  wire                                  s_axis_w13_tvalid,
  output wire                                  s_axis_w13_tready,
  input  wire [C_S_AXIS_W13_TDATA_WIDTH-1:0]   s_axis_w13_tdata ,
  input  wire [C_S_AXIS_W13_TDATA_WIDTH/8-1:0] s_axis_w13_tkeep ,
  input  wire                                  s_axis_w13_tlast ,
  // AXI4-Stream (slave) interface s_axis_w14
  input  wire                                  s_axis_w14_tvalid,
  output wire                                  s_axis_w14_tready,
  input  wire [C_S_AXIS_W14_TDATA_WIDTH-1:0]   s_axis_w14_tdata ,
  input  wire [C_S_AXIS_W14_TDATA_WIDTH/8-1:0] s_axis_w14_tkeep ,
  input  wire                                  s_axis_w14_tlast ,
  // AXI4-Stream (slave) interface s_axis_w15
  input  wire                                  s_axis_w15_tvalid,
  output wire                                  s_axis_w15_tready,
  input  wire [C_S_AXIS_W15_TDATA_WIDTH-1:0]   s_axis_w15_tdata ,
  input  wire [C_S_AXIS_W15_TDATA_WIDTH/8-1:0] s_axis_w15_tkeep ,
  input  wire                                  s_axis_w15_tlast ,
  // AXI4-Stream (slave) interface s_axis_ind0
  input  wire                                  s_axis_ind0_tvalid,
  output wire                                  s_axis_ind0_tready,
  input  wire [C_S_AXIS_IND0_TDATA_WIDTH-1:0]   s_axis_ind0_tdata ,
  input  wire [C_S_AXIS_IND0_TDATA_WIDTH/8-1:0] s_axis_ind0_tkeep ,
  input  wire                                  s_axis_ind0_tlast ,
  // AXI4-Stream (slave) interface s_axis_ind1
  input  wire                                  s_axis_ind1_tvalid,
  output wire                                  s_axis_ind1_tready,
  input  wire [C_S_AXIS_IND1_TDATA_WIDTH-1:0]   s_axis_ind1_tdata ,
  input  wire [C_S_AXIS_IND1_TDATA_WIDTH/8-1:0] s_axis_ind1_tkeep ,
  input  wire                                  s_axis_ind1_tlast ,
  // AXI4-Stream (slave) interface s_axis_ind2
  input  wire                                  s_axis_ind2_tvalid,
  output wire                                  s_axis_ind2_tready,
  input  wire [C_S_AXIS_IND2_TDATA_WIDTH-1:0]   s_axis_ind2_tdata ,
  input  wire [C_S_AXIS_IND2_TDATA_WIDTH/8-1:0] s_axis_ind2_tkeep ,
  input  wire                                  s_axis_ind2_tlast ,
  // AXI4-Stream (slave) interface s_axis_ind3
  input  wire                                  s_axis_ind3_tvalid,
  output wire                                  s_axis_ind3_tready,
  input  wire [C_S_AXIS_IND3_TDATA_WIDTH-1:0]   s_axis_ind3_tdata ,
  input  wire [C_S_AXIS_IND3_TDATA_WIDTH/8-1:0] s_axis_ind3_tkeep ,
  input  wire                                  s_axis_ind3_tlast ,
  // AXI4-Stream (slave) interface s_axis_ind4
  input  wire                                  s_axis_ind4_tvalid,
  output wire                                  s_axis_ind4_tready,
  input  wire [C_S_AXIS_IND4_TDATA_WIDTH-1:0]   s_axis_ind4_tdata ,
  input  wire [C_S_AXIS_IND4_TDATA_WIDTH/8-1:0] s_axis_ind4_tkeep ,
  input  wire                                  s_axis_ind4_tlast ,
  // AXI4-Stream (slave) interface s_axis_ind5
  input  wire                                  s_axis_ind5_tvalid,
  output wire                                  s_axis_ind5_tready,
  input  wire [C_S_AXIS_IND5_TDATA_WIDTH-1:0]   s_axis_ind5_tdata ,
  input  wire [C_S_AXIS_IND5_TDATA_WIDTH/8-1:0] s_axis_ind5_tkeep ,
  input  wire                                  s_axis_ind5_tlast ,
  // AXI4-Stream (slave) interface s_axis_a0
  input  wire                                  s_axis_a0_tvalid,
  output wire                                  s_axis_a0_tready,
  input  wire [C_S_AXIS_A0_TDATA_WIDTH-1:0]   s_axis_a0_tdata ,
  input  wire [C_S_AXIS_A0_TDATA_WIDTH/8-1:0] s_axis_a0_tkeep ,
  input  wire                                  s_axis_a0_tlast ,
  // AXI4-Stream (slave) interface s_axis_a1
  input  wire                                  s_axis_a1_tvalid,
  output wire                                  s_axis_a1_tready,
  input  wire [C_S_AXIS_A1_TDATA_WIDTH-1:0]   s_axis_a1_tdata ,
  input  wire [C_S_AXIS_A1_TDATA_WIDTH/8-1:0] s_axis_a1_tkeep ,
  input  wire                                  s_axis_a1_tlast ,
  // AXI4-Stream (master) interface m_axis_c0
  output wire                                  m_axis_c0_tvalid,
  input  wire                                  m_axis_c0_tready,
  output wire [C_M_AXIS_C0_TDATA_WIDTH-1:0]   m_axis_c0_tdata ,
  output wire [C_M_AXIS_C0_TDATA_WIDTH/8-1:0] m_axis_c0_tkeep ,
  output wire                                  m_axis_c0_tlast ,
  // AXI4-Stream (master) interface m_axis_c1
  output wire                                  m_axis_c1_tvalid,
  input  wire                                  m_axis_c1_tready,
  output wire [C_M_AXIS_C1_TDATA_WIDTH-1:0]   m_axis_c1_tdata ,
  output wire [C_M_AXIS_C1_TDATA_WIDTH/8-1:0] m_axis_c1_tkeep ,
  output wire                                  m_axis_c1_tlast ,
  // AXI4-Stream (master) interface m_axis_c2
  output wire                                  m_axis_c2_tvalid,
  input  wire                                  m_axis_c2_tready,
  output wire [C_M_AXIS_C2_TDATA_WIDTH-1:0]   m_axis_c2_tdata ,
  output wire [C_M_AXIS_C2_TDATA_WIDTH/8-1:0] m_axis_c2_tkeep ,
  output wire                                  m_axis_c2_tlast ,
  // AXI4-Stream (master) interface m_axis_c3
  output wire                                  m_axis_c3_tvalid,
  input  wire                                  m_axis_c3_tready,
  output wire [C_M_AXIS_C3_TDATA_WIDTH-1:0]   m_axis_c3_tdata ,
  output wire [C_M_AXIS_C3_TDATA_WIDTH/8-1:0] m_axis_c3_tkeep ,
  output wire                                  m_axis_c3_tlast ,
  // AXI4-Stream (master) interface m_axis_c4
  output wire                                  m_axis_c4_tvalid,
  input  wire                                  m_axis_c4_tready,
  output wire [C_M_AXIS_C4_TDATA_WIDTH-1:0]   m_axis_c4_tdata ,
  output wire [C_M_AXIS_C4_TDATA_WIDTH/8-1:0] m_axis_c4_tkeep ,
  output wire                                  m_axis_c4_tlast ,
  // AXI4-Stream (master) interface m_axis_c5
  output wire                                  m_axis_c5_tvalid,
  input  wire                                  m_axis_c5_tready,
  output wire [C_M_AXIS_C5_TDATA_WIDTH-1:0]   m_axis_c5_tdata ,
  output wire [C_M_AXIS_C5_TDATA_WIDTH/8-1:0] m_axis_c5_tkeep ,
  output wire                                  m_axis_c5_tlast ,
  // AXI4-Stream (master) interface m_axis_c6
  output wire                                  m_axis_c6_tvalid,
  input  wire                                  m_axis_c6_tready,
  output wire [C_M_AXIS_C6_TDATA_WIDTH-1:0]   m_axis_c6_tdata ,
  output wire [C_M_AXIS_C6_TDATA_WIDTH/8-1:0] m_axis_c6_tkeep ,
  output wire                                  m_axis_c6_tlast ,
  // AXI4-Stream (master) interface m_axis_c7
  output wire                                  m_axis_c7_tvalid,
  input  wire                                  m_axis_c7_tready,
  output wire [C_M_AXIS_C7_TDATA_WIDTH-1:0]   m_axis_c7_tdata ,
  output wire [C_M_AXIS_C7_TDATA_WIDTH/8-1:0] m_axis_c7_tkeep ,
  output wire                                  m_axis_c7_tlast 
);

///////////////////////////////////////////////////////////////////////////////
// Begin control interface RTL.  Modifying not recommended.
///////////////////////////////////////////////////////////////////////////////
// (none -- this is an ap_ctrl_none free-running kernel: no s_axi_control, no
//  ap_start/ap_done. It runs from the moment the xclbin is programmed and
//  interacts with the rest of the system only through the streams above.)

///////////////////////////////////////////////////////////////////////////////
// Kernel logic.
///////////////////////////////////////////////////////////////////////////////
two2N_axis inst_gemv (
  .ap_clk            ( ap_clk            ),
  .ap_rst_n          ( ap_rst_n          ),

  .s_axis_w0_tvalid ( s_axis_w0_tvalid ),
  .s_axis_w0_tready ( s_axis_w0_tready ),
  .s_axis_w0_tdata  ( s_axis_w0_tdata  ),
  .s_axis_w0_tkeep  ( s_axis_w0_tkeep  ),
  .s_axis_w0_tlast  ( s_axis_w0_tlast  ),

  .s_axis_w1_tvalid ( s_axis_w1_tvalid ),
  .s_axis_w1_tready ( s_axis_w1_tready ),
  .s_axis_w1_tdata  ( s_axis_w1_tdata  ),
  .s_axis_w1_tkeep  ( s_axis_w1_tkeep  ),
  .s_axis_w1_tlast  ( s_axis_w1_tlast  ),

  .s_axis_w2_tvalid ( s_axis_w2_tvalid ),
  .s_axis_w2_tready ( s_axis_w2_tready ),
  .s_axis_w2_tdata  ( s_axis_w2_tdata  ),
  .s_axis_w2_tkeep  ( s_axis_w2_tkeep  ),
  .s_axis_w2_tlast  ( s_axis_w2_tlast  ),

  .s_axis_w3_tvalid ( s_axis_w3_tvalid ),
  .s_axis_w3_tready ( s_axis_w3_tready ),
  .s_axis_w3_tdata  ( s_axis_w3_tdata  ),
  .s_axis_w3_tkeep  ( s_axis_w3_tkeep  ),
  .s_axis_w3_tlast  ( s_axis_w3_tlast  ),

  .s_axis_w4_tvalid ( s_axis_w4_tvalid ),
  .s_axis_w4_tready ( s_axis_w4_tready ),
  .s_axis_w4_tdata  ( s_axis_w4_tdata  ),
  .s_axis_w4_tkeep  ( s_axis_w4_tkeep  ),
  .s_axis_w4_tlast  ( s_axis_w4_tlast  ),

  .s_axis_w5_tvalid ( s_axis_w5_tvalid ),
  .s_axis_w5_tready ( s_axis_w5_tready ),
  .s_axis_w5_tdata  ( s_axis_w5_tdata  ),
  .s_axis_w5_tkeep  ( s_axis_w5_tkeep  ),
  .s_axis_w5_tlast  ( s_axis_w5_tlast  ),

  .s_axis_w6_tvalid ( s_axis_w6_tvalid ),
  .s_axis_w6_tready ( s_axis_w6_tready ),
  .s_axis_w6_tdata  ( s_axis_w6_tdata  ),
  .s_axis_w6_tkeep  ( s_axis_w6_tkeep  ),
  .s_axis_w6_tlast  ( s_axis_w6_tlast  ),

  .s_axis_w7_tvalid ( s_axis_w7_tvalid ),
  .s_axis_w7_tready ( s_axis_w7_tready ),
  .s_axis_w7_tdata  ( s_axis_w7_tdata  ),
  .s_axis_w7_tkeep  ( s_axis_w7_tkeep  ),
  .s_axis_w7_tlast  ( s_axis_w7_tlast  ),

  .s_axis_w8_tvalid ( s_axis_w8_tvalid ),
  .s_axis_w8_tready ( s_axis_w8_tready ),
  .s_axis_w8_tdata  ( s_axis_w8_tdata  ),
  .s_axis_w8_tkeep  ( s_axis_w8_tkeep  ),
  .s_axis_w8_tlast  ( s_axis_w8_tlast  ),

  .s_axis_w9_tvalid ( s_axis_w9_tvalid ),
  .s_axis_w9_tready ( s_axis_w9_tready ),
  .s_axis_w9_tdata  ( s_axis_w9_tdata  ),
  .s_axis_w9_tkeep  ( s_axis_w9_tkeep  ),
  .s_axis_w9_tlast  ( s_axis_w9_tlast  ),

  .s_axis_w10_tvalid ( s_axis_w10_tvalid ),
  .s_axis_w10_tready ( s_axis_w10_tready ),
  .s_axis_w10_tdata  ( s_axis_w10_tdata  ),
  .s_axis_w10_tkeep  ( s_axis_w10_tkeep  ),
  .s_axis_w10_tlast  ( s_axis_w10_tlast  ),

  .s_axis_w11_tvalid ( s_axis_w11_tvalid ),
  .s_axis_w11_tready ( s_axis_w11_tready ),
  .s_axis_w11_tdata  ( s_axis_w11_tdata  ),
  .s_axis_w11_tkeep  ( s_axis_w11_tkeep  ),
  .s_axis_w11_tlast  ( s_axis_w11_tlast  ),

  .s_axis_w12_tvalid ( s_axis_w12_tvalid ),
  .s_axis_w12_tready ( s_axis_w12_tready ),
  .s_axis_w12_tdata  ( s_axis_w12_tdata  ),
  .s_axis_w12_tkeep  ( s_axis_w12_tkeep  ),
  .s_axis_w12_tlast  ( s_axis_w12_tlast  ),

  .s_axis_w13_tvalid ( s_axis_w13_tvalid ),
  .s_axis_w13_tready ( s_axis_w13_tready ),
  .s_axis_w13_tdata  ( s_axis_w13_tdata  ),
  .s_axis_w13_tkeep  ( s_axis_w13_tkeep  ),
  .s_axis_w13_tlast  ( s_axis_w13_tlast  ),

  .s_axis_w14_tvalid ( s_axis_w14_tvalid ),
  .s_axis_w14_tready ( s_axis_w14_tready ),
  .s_axis_w14_tdata  ( s_axis_w14_tdata  ),
  .s_axis_w14_tkeep  ( s_axis_w14_tkeep  ),
  .s_axis_w14_tlast  ( s_axis_w14_tlast  ),

  .s_axis_w15_tvalid ( s_axis_w15_tvalid ),
  .s_axis_w15_tready ( s_axis_w15_tready ),
  .s_axis_w15_tdata  ( s_axis_w15_tdata  ),
  .s_axis_w15_tkeep  ( s_axis_w15_tkeep  ),
  .s_axis_w15_tlast  ( s_axis_w15_tlast  ),

  .s_axis_ind0_tvalid ( s_axis_ind0_tvalid ),
  .s_axis_ind0_tready ( s_axis_ind0_tready ),
  .s_axis_ind0_tdata  ( s_axis_ind0_tdata  ),
  .s_axis_ind0_tkeep  ( s_axis_ind0_tkeep  ),
  .s_axis_ind0_tlast  ( s_axis_ind0_tlast  ),

  .s_axis_ind1_tvalid ( s_axis_ind1_tvalid ),
  .s_axis_ind1_tready ( s_axis_ind1_tready ),
  .s_axis_ind1_tdata  ( s_axis_ind1_tdata  ),
  .s_axis_ind1_tkeep  ( s_axis_ind1_tkeep  ),
  .s_axis_ind1_tlast  ( s_axis_ind1_tlast  ),

  .s_axis_ind2_tvalid ( s_axis_ind2_tvalid ),
  .s_axis_ind2_tready ( s_axis_ind2_tready ),
  .s_axis_ind2_tdata  ( s_axis_ind2_tdata  ),
  .s_axis_ind2_tkeep  ( s_axis_ind2_tkeep  ),
  .s_axis_ind2_tlast  ( s_axis_ind2_tlast  ),

  .s_axis_ind3_tvalid ( s_axis_ind3_tvalid ),
  .s_axis_ind3_tready ( s_axis_ind3_tready ),
  .s_axis_ind3_tdata  ( s_axis_ind3_tdata  ),
  .s_axis_ind3_tkeep  ( s_axis_ind3_tkeep  ),
  .s_axis_ind3_tlast  ( s_axis_ind3_tlast  ),

  .s_axis_ind4_tvalid ( s_axis_ind4_tvalid ),
  .s_axis_ind4_tready ( s_axis_ind4_tready ),
  .s_axis_ind4_tdata  ( s_axis_ind4_tdata  ),
  .s_axis_ind4_tkeep  ( s_axis_ind4_tkeep  ),
  .s_axis_ind4_tlast  ( s_axis_ind4_tlast  ),

  .s_axis_ind5_tvalid ( s_axis_ind5_tvalid ),
  .s_axis_ind5_tready ( s_axis_ind5_tready ),
  .s_axis_ind5_tdata  ( s_axis_ind5_tdata  ),
  .s_axis_ind5_tkeep  ( s_axis_ind5_tkeep  ),
  .s_axis_ind5_tlast  ( s_axis_ind5_tlast  ),

  .s_axis_a0_tvalid ( s_axis_a0_tvalid ),
  .s_axis_a0_tready ( s_axis_a0_tready ),
  .s_axis_a0_tdata  ( s_axis_a0_tdata  ),
  .s_axis_a0_tkeep  ( s_axis_a0_tkeep  ),
  .s_axis_a0_tlast  ( s_axis_a0_tlast  ),

  .s_axis_a1_tvalid ( s_axis_a1_tvalid ),
  .s_axis_a1_tready ( s_axis_a1_tready ),
  .s_axis_a1_tdata  ( s_axis_a1_tdata  ),
  .s_axis_a1_tkeep  ( s_axis_a1_tkeep  ),
  .s_axis_a1_tlast  ( s_axis_a1_tlast  ),

  .m_axis_c0_tvalid ( m_axis_c0_tvalid ),
  .m_axis_c0_tready ( m_axis_c0_tready ),
  .m_axis_c0_tdata  ( m_axis_c0_tdata  ),
  .m_axis_c0_tkeep  ( m_axis_c0_tkeep  ),
  .m_axis_c0_tlast  ( m_axis_c0_tlast  ),

  .m_axis_c1_tvalid ( m_axis_c1_tvalid ),
  .m_axis_c1_tready ( m_axis_c1_tready ),
  .m_axis_c1_tdata  ( m_axis_c1_tdata  ),
  .m_axis_c1_tkeep  ( m_axis_c1_tkeep  ),
  .m_axis_c1_tlast  ( m_axis_c1_tlast  ),

  .m_axis_c2_tvalid ( m_axis_c2_tvalid ),
  .m_axis_c2_tready ( m_axis_c2_tready ),
  .m_axis_c2_tdata  ( m_axis_c2_tdata  ),
  .m_axis_c2_tkeep  ( m_axis_c2_tkeep  ),
  .m_axis_c2_tlast  ( m_axis_c2_tlast  ),

  .m_axis_c3_tvalid ( m_axis_c3_tvalid ),
  .m_axis_c3_tready ( m_axis_c3_tready ),
  .m_axis_c3_tdata  ( m_axis_c3_tdata  ),
  .m_axis_c3_tkeep  ( m_axis_c3_tkeep  ),
  .m_axis_c3_tlast  ( m_axis_c3_tlast  ),

  .m_axis_c4_tvalid ( m_axis_c4_tvalid ),
  .m_axis_c4_tready ( m_axis_c4_tready ),
  .m_axis_c4_tdata  ( m_axis_c4_tdata  ),
  .m_axis_c4_tkeep  ( m_axis_c4_tkeep  ),
  .m_axis_c4_tlast  ( m_axis_c4_tlast  ),

  .m_axis_c5_tvalid ( m_axis_c5_tvalid ),
  .m_axis_c5_tready ( m_axis_c5_tready ),
  .m_axis_c5_tdata  ( m_axis_c5_tdata  ),
  .m_axis_c5_tkeep  ( m_axis_c5_tkeep  ),
  .m_axis_c5_tlast  ( m_axis_c5_tlast  ),

  .m_axis_c6_tvalid ( m_axis_c6_tvalid ),
  .m_axis_c6_tready ( m_axis_c6_tready ),
  .m_axis_c6_tdata  ( m_axis_c6_tdata  ),
  .m_axis_c6_tkeep  ( m_axis_c6_tkeep  ),
  .m_axis_c6_tlast  ( m_axis_c6_tlast  ),

  .m_axis_c7_tvalid ( m_axis_c7_tvalid ),
  .m_axis_c7_tready ( m_axis_c7_tready ),
  .m_axis_c7_tdata  ( m_axis_c7_tdata  ),
  .m_axis_c7_tkeep  ( m_axis_c7_tkeep  ),
  .m_axis_c7_tlast  ( m_axis_c7_tlast  )
);

endmodule
`default_nettype wire
