library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

-- ----------------------------------------------------------------------------
-- Engineer: Sozos Koulas @ National Technical University of Athens
--
-- two2N_axis -- AXI4-Stream splitter wrapper around two2N (the 2:M sparse engine).
--
-- GENERATED by make_family_build.py for the 4x32 configuration
-- (4 cores x 32 blocks = 128 blocks, 1024 DSPs, 32 HBM pseudo-channels).
-- Do not hand-edit: regenerate instead, or the generics and the port list drift
-- apart and the mismatch is silent.
--
-- WHY THIS EXISTS (INTEGRATION_PLAN.md 0.2b):
-- two2N declares its streams BUNDLED -- s_axis_w_tdata is one 4096-bit port with
-- a 16-bit tvalid/tready/tlast vector, and so on. The Vitis RTL Kernel Wizard
-- needs 32 SEPARATE, properly named AXIS interfaces so the packager can infer
-- them. THIS FILE CONTAINS NO LOGIC -- pure re-wiring:
--   1. slice tdata little-endian  -- PC k = tdata(256k+255 downto 256k)
--   2. slice the tvalid/tready/tlast vectors to scalars -- bit k = PC k
--   3. drive every master tkeep all-1s; ignore every slave tkeep
--      (UG1393: TKEEP must be all 1s when TLAST is 0 and may never be all
--       zeros; this engine has no ragged tails -- every beat is a full 256-bit
--       PC word)
--   4. ACCEPT AND DISCARD the index TLAST -- see the note below
--
-- ⚠️ THE GENERIC DEFAULTS BELOW ARE LOAD-BEARING. krnl_gemv_sparse.v is Verilog
-- instantiating this VHDL entity, and Verilog cannot pass VHDL generics. These
-- defaults ARE the configuration. Change them and nothing warns you.
--
-- INDEX TLAST. two2N has s_axis_ind_tvalid / _tready / _tdata but deliberately
-- NO s_axis_ind_tlast: the index stream carries no end-of-packet meaning for the
-- engine (weight TLAST marks end-of-calculation, activation TLAST marks
-- end-of-vector). The AXIS rules still require the signal to exist on the
-- interface, and krnl_mm2s emits one on its last beat like every other channel.
-- So the wrapper DECLARES the 6 index tlast input(s) and leaves them
-- unconnected. Nothing is fabricated; the marker is simply not meaningful here.
--
-- ASSIGNMENT STYLE differs from the hand-written 8x8 file: this generator emits
-- ELEMENT-WISE slice assignments where that file used one descending
-- concatenation. The two are exactly equivalent in VHDL, and element-wise has no
-- special case at N=1 (T=16 has a single index PC and a single output PC).
--
-- The verified two2N netlist below is untouched, so an OOC synthesis of this
-- wrapper must report utilisation and WNS IDENTICAL to the bare two2N numbers.
-- A wrapper that costs a LUT is a wrapper with logic in it.
-- ----------------------------------------------------------------------------

entity two2N_axis is
    generic(
        EL_SIZE     : integer := 16;    -- Bit size of each element
        W_IDX       : integer := 64;    -- matrix elements per core = 2 x BLOCKS_NUM
        A_IDX       : integer := 32;    -- vector elements (the window)
        IND_NUM     : integer := 10;    -- index bits per block
        BLOCKS_NUM  : integer := 32;    -- C blocks per core (2 elements each)
        CORES_NUM   : integer := 4;    -- C Cores

        PC_WIDTH    : integer := 256;   -- HBM pseudo-channel data width
        W_PCS       : integer := 16;    -- weight PCs (16*256 = 4096 bits)
        A_PCS       : integer := 2;    -- activation PCs
        IND_PCS     : integer := 6;    -- index PCs (6*256 = 1536, 1280 used)
        C_PCS       : integer := 8;    -- output PCs (8*256 = 2048 bits)
        IND_BITS    : integer := 1280    -- useful index bits (remainder is padding)
    );
    port(
        ap_clk   : in std_logic;
        ap_rst_n : in std_logic;

        -- ---- Weights : 16 slave AXIS channels ----
        s_axis_w0_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_w0_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_w0_tvalid : in  std_logic;
        s_axis_w0_tready : out std_logic;
        s_axis_w0_tlast  : in  std_logic;

        s_axis_w1_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_w1_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_w1_tvalid : in  std_logic;
        s_axis_w1_tready : out std_logic;
        s_axis_w1_tlast  : in  std_logic;

        s_axis_w2_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_w2_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_w2_tvalid : in  std_logic;
        s_axis_w2_tready : out std_logic;
        s_axis_w2_tlast  : in  std_logic;

        s_axis_w3_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_w3_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_w3_tvalid : in  std_logic;
        s_axis_w3_tready : out std_logic;
        s_axis_w3_tlast  : in  std_logic;

        s_axis_w4_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_w4_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_w4_tvalid : in  std_logic;
        s_axis_w4_tready : out std_logic;
        s_axis_w4_tlast  : in  std_logic;

        s_axis_w5_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_w5_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_w5_tvalid : in  std_logic;
        s_axis_w5_tready : out std_logic;
        s_axis_w5_tlast  : in  std_logic;

        s_axis_w6_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_w6_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_w6_tvalid : in  std_logic;
        s_axis_w6_tready : out std_logic;
        s_axis_w6_tlast  : in  std_logic;

        s_axis_w7_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_w7_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_w7_tvalid : in  std_logic;
        s_axis_w7_tready : out std_logic;
        s_axis_w7_tlast  : in  std_logic;

        s_axis_w8_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_w8_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_w8_tvalid : in  std_logic;
        s_axis_w8_tready : out std_logic;
        s_axis_w8_tlast  : in  std_logic;

        s_axis_w9_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_w9_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_w9_tvalid : in  std_logic;
        s_axis_w9_tready : out std_logic;
        s_axis_w9_tlast  : in  std_logic;

        s_axis_w10_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_w10_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_w10_tvalid : in  std_logic;
        s_axis_w10_tready : out std_logic;
        s_axis_w10_tlast  : in  std_logic;

        s_axis_w11_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_w11_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_w11_tvalid : in  std_logic;
        s_axis_w11_tready : out std_logic;
        s_axis_w11_tlast  : in  std_logic;

        s_axis_w12_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_w12_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_w12_tvalid : in  std_logic;
        s_axis_w12_tready : out std_logic;
        s_axis_w12_tlast  : in  std_logic;

        s_axis_w13_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_w13_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_w13_tvalid : in  std_logic;
        s_axis_w13_tready : out std_logic;
        s_axis_w13_tlast  : in  std_logic;

        s_axis_w14_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_w14_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_w14_tvalid : in  std_logic;
        s_axis_w14_tready : out std_logic;
        s_axis_w14_tlast  : in  std_logic;

        s_axis_w15_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_w15_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_w15_tvalid : in  std_logic;
        s_axis_w15_tready : out std_logic;
        s_axis_w15_tlast  : in  std_logic;

        -- ---- Indices : 6 slave AXIS channel(s) ----
        -- tlast is declared because the AXIS rules require it and krnl_mm2s
        -- drives it; the engine has no such port, so it is left unconnected.
        s_axis_ind0_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_ind0_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_ind0_tvalid : in  std_logic;
        s_axis_ind0_tready : out std_logic;
        s_axis_ind0_tlast  : in  std_logic;

        s_axis_ind1_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_ind1_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_ind1_tvalid : in  std_logic;
        s_axis_ind1_tready : out std_logic;
        s_axis_ind1_tlast  : in  std_logic;

        s_axis_ind2_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_ind2_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_ind2_tvalid : in  std_logic;
        s_axis_ind2_tready : out std_logic;
        s_axis_ind2_tlast  : in  std_logic;

        s_axis_ind3_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_ind3_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_ind3_tvalid : in  std_logic;
        s_axis_ind3_tready : out std_logic;
        s_axis_ind3_tlast  : in  std_logic;

        s_axis_ind4_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_ind4_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_ind4_tvalid : in  std_logic;
        s_axis_ind4_tready : out std_logic;
        s_axis_ind4_tlast  : in  std_logic;

        s_axis_ind5_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_ind5_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_ind5_tvalid : in  std_logic;
        s_axis_ind5_tready : out std_logic;
        s_axis_ind5_tlast  : in  std_logic;

        -- ---- Activations : 2 slave AXIS channels ----
        s_axis_a0_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_a0_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_a0_tvalid : in  std_logic;
        s_axis_a0_tready : out std_logic;
        s_axis_a0_tlast  : in  std_logic;

        s_axis_a1_tdata  : in  std_logic_vector(PC_WIDTH-1 downto 0);
        s_axis_a1_tkeep  : in  std_logic_vector(PC_WIDTH/8-1 downto 0);
        s_axis_a1_tvalid : in  std_logic;
        s_axis_a1_tready : out std_logic;
        s_axis_a1_tlast  : in  std_logic;

        -- ---- Output : 8 master AXIS channel(s) ----
        m_axis_c0_tdata  : out std_logic_vector(PC_WIDTH-1 downto 0);
        m_axis_c0_tkeep  : out std_logic_vector(PC_WIDTH/8-1 downto 0);
        m_axis_c0_tvalid : out std_logic;
        m_axis_c0_tready : in  std_logic;
        m_axis_c0_tlast  : out std_logic;

        m_axis_c1_tdata  : out std_logic_vector(PC_WIDTH-1 downto 0);
        m_axis_c1_tkeep  : out std_logic_vector(PC_WIDTH/8-1 downto 0);
        m_axis_c1_tvalid : out std_logic;
        m_axis_c1_tready : in  std_logic;
        m_axis_c1_tlast  : out std_logic;

        m_axis_c2_tdata  : out std_logic_vector(PC_WIDTH-1 downto 0);
        m_axis_c2_tkeep  : out std_logic_vector(PC_WIDTH/8-1 downto 0);
        m_axis_c2_tvalid : out std_logic;
        m_axis_c2_tready : in  std_logic;
        m_axis_c2_tlast  : out std_logic;

        m_axis_c3_tdata  : out std_logic_vector(PC_WIDTH-1 downto 0);
        m_axis_c3_tkeep  : out std_logic_vector(PC_WIDTH/8-1 downto 0);
        m_axis_c3_tvalid : out std_logic;
        m_axis_c3_tready : in  std_logic;
        m_axis_c3_tlast  : out std_logic;

        m_axis_c4_tdata  : out std_logic_vector(PC_WIDTH-1 downto 0);
        m_axis_c4_tkeep  : out std_logic_vector(PC_WIDTH/8-1 downto 0);
        m_axis_c4_tvalid : out std_logic;
        m_axis_c4_tready : in  std_logic;
        m_axis_c4_tlast  : out std_logic;

        m_axis_c5_tdata  : out std_logic_vector(PC_WIDTH-1 downto 0);
        m_axis_c5_tkeep  : out std_logic_vector(PC_WIDTH/8-1 downto 0);
        m_axis_c5_tvalid : out std_logic;
        m_axis_c5_tready : in  std_logic;
        m_axis_c5_tlast  : out std_logic;

        m_axis_c6_tdata  : out std_logic_vector(PC_WIDTH-1 downto 0);
        m_axis_c6_tkeep  : out std_logic_vector(PC_WIDTH/8-1 downto 0);
        m_axis_c6_tvalid : out std_logic;
        m_axis_c6_tready : in  std_logic;
        m_axis_c6_tlast  : out std_logic;

        m_axis_c7_tdata  : out std_logic_vector(PC_WIDTH-1 downto 0);
        m_axis_c7_tkeep  : out std_logic_vector(PC_WIDTH/8-1 downto 0);
        m_axis_c7_tvalid : out std_logic;
        m_axis_c7_tready : in  std_logic;
        m_axis_c7_tlast  : out std_logic
    );
end entity two2N_axis;


architecture rewire of two2N_axis is

    -- bundled buses, exactly as two2N declares them
    signal w_tdata  : std_logic_vector(W_PCS*PC_WIDTH-1 downto 0);
    signal w_tvalid : std_logic_vector(W_PCS-1 downto 0);
    signal w_tready : std_logic_vector(W_PCS-1 downto 0);
    signal w_tlast  : std_logic_vector(W_PCS-1 downto 0);

    signal i_tdata  : std_logic_vector(IND_PCS*PC_WIDTH-1 downto 0);
    signal i_tvalid : std_logic_vector(IND_PCS-1 downto 0);
    signal i_tready : std_logic_vector(IND_PCS-1 downto 0);

    signal a_tdata  : std_logic_vector(A_PCS*PC_WIDTH-1 downto 0);
    signal a_tvalid : std_logic_vector(A_PCS-1 downto 0);
    signal a_tready : std_logic_vector(A_PCS-1 downto 0);
    signal a_tlast  : std_logic_vector(A_PCS-1 downto 0);

    signal c_tdata  : std_logic_vector((BLOCKS_NUM*CORES_NUM*EL_SIZE)-1 downto 0);
    signal c_tvalid : std_logic_vector(C_PCS-1 downto 0);
    signal c_tready : std_logic_vector(C_PCS-1 downto 0);
    signal c_tlast  : std_logic_vector(C_PCS-1 downto 0);

    constant KEEP_ALL : std_logic_vector(PC_WIDTH/8-1 downto 0) := (others => '1');

begin

    -- =======================================================================
    -- 1. JOIN the per-channel slave ports into the bundled buses.
    --    Little-endian: PC 0 occupies the LSBs, matching HBM/AXI byte order
    --    and the convention every other module in this design follows.
    --    The 2-bit Sparsity code rides in the LAST index PC's padding, bits
    --    [1281:1280] of the joined index word -- it is buffer CONTENT written by
    --    the host packer and needs nothing from this wrapper.
    -- =======================================================================
    w_tdata(((0+1)*PC_WIDTH)-1 downto 0*PC_WIDTH) <= s_axis_w0_tdata;
    w_tdata(((1+1)*PC_WIDTH)-1 downto 1*PC_WIDTH) <= s_axis_w1_tdata;
    w_tdata(((2+1)*PC_WIDTH)-1 downto 2*PC_WIDTH) <= s_axis_w2_tdata;
    w_tdata(((3+1)*PC_WIDTH)-1 downto 3*PC_WIDTH) <= s_axis_w3_tdata;
    w_tdata(((4+1)*PC_WIDTH)-1 downto 4*PC_WIDTH) <= s_axis_w4_tdata;
    w_tdata(((5+1)*PC_WIDTH)-1 downto 5*PC_WIDTH) <= s_axis_w5_tdata;
    w_tdata(((6+1)*PC_WIDTH)-1 downto 6*PC_WIDTH) <= s_axis_w6_tdata;
    w_tdata(((7+1)*PC_WIDTH)-1 downto 7*PC_WIDTH) <= s_axis_w7_tdata;
    w_tdata(((8+1)*PC_WIDTH)-1 downto 8*PC_WIDTH) <= s_axis_w8_tdata;
    w_tdata(((9+1)*PC_WIDTH)-1 downto 9*PC_WIDTH) <= s_axis_w9_tdata;
    w_tdata(((10+1)*PC_WIDTH)-1 downto 10*PC_WIDTH) <= s_axis_w10_tdata;
    w_tdata(((11+1)*PC_WIDTH)-1 downto 11*PC_WIDTH) <= s_axis_w11_tdata;
    w_tdata(((12+1)*PC_WIDTH)-1 downto 12*PC_WIDTH) <= s_axis_w12_tdata;
    w_tdata(((13+1)*PC_WIDTH)-1 downto 13*PC_WIDTH) <= s_axis_w13_tdata;
    w_tdata(((14+1)*PC_WIDTH)-1 downto 14*PC_WIDTH) <= s_axis_w14_tdata;
    w_tdata(((15+1)*PC_WIDTH)-1 downto 15*PC_WIDTH) <= s_axis_w15_tdata;

    w_tvalid(0) <= s_axis_w0_tvalid;
    w_tvalid(1) <= s_axis_w1_tvalid;
    w_tvalid(2) <= s_axis_w2_tvalid;
    w_tvalid(3) <= s_axis_w3_tvalid;
    w_tvalid(4) <= s_axis_w4_tvalid;
    w_tvalid(5) <= s_axis_w5_tvalid;
    w_tvalid(6) <= s_axis_w6_tvalid;
    w_tvalid(7) <= s_axis_w7_tvalid;
    w_tvalid(8) <= s_axis_w8_tvalid;
    w_tvalid(9) <= s_axis_w9_tvalid;
    w_tvalid(10) <= s_axis_w10_tvalid;
    w_tvalid(11) <= s_axis_w11_tvalid;
    w_tvalid(12) <= s_axis_w12_tvalid;
    w_tvalid(13) <= s_axis_w13_tvalid;
    w_tvalid(14) <= s_axis_w14_tvalid;
    w_tvalid(15) <= s_axis_w15_tvalid;

    w_tlast(0)  <= s_axis_w0_tlast;
    w_tlast(1)  <= s_axis_w1_tlast;
    w_tlast(2)  <= s_axis_w2_tlast;
    w_tlast(3)  <= s_axis_w3_tlast;
    w_tlast(4)  <= s_axis_w4_tlast;
    w_tlast(5)  <= s_axis_w5_tlast;
    w_tlast(6)  <= s_axis_w6_tlast;
    w_tlast(7)  <= s_axis_w7_tlast;
    w_tlast(8)  <= s_axis_w8_tlast;
    w_tlast(9)  <= s_axis_w9_tlast;
    w_tlast(10)  <= s_axis_w10_tlast;
    w_tlast(11)  <= s_axis_w11_tlast;
    w_tlast(12)  <= s_axis_w12_tlast;
    w_tlast(13)  <= s_axis_w13_tlast;
    w_tlast(14)  <= s_axis_w14_tlast;
    w_tlast(15)  <= s_axis_w15_tlast;

    i_tdata(((0+1)*PC_WIDTH)-1 downto 0*PC_WIDTH) <= s_axis_ind0_tdata;
    i_tdata(((1+1)*PC_WIDTH)-1 downto 1*PC_WIDTH) <= s_axis_ind1_tdata;
    i_tdata(((2+1)*PC_WIDTH)-1 downto 2*PC_WIDTH) <= s_axis_ind2_tdata;
    i_tdata(((3+1)*PC_WIDTH)-1 downto 3*PC_WIDTH) <= s_axis_ind3_tdata;
    i_tdata(((4+1)*PC_WIDTH)-1 downto 4*PC_WIDTH) <= s_axis_ind4_tdata;
    i_tdata(((5+1)*PC_WIDTH)-1 downto 5*PC_WIDTH) <= s_axis_ind5_tdata;

    i_tvalid(0) <= s_axis_ind0_tvalid;
    i_tvalid(1) <= s_axis_ind1_tvalid;
    i_tvalid(2) <= s_axis_ind2_tvalid;
    i_tvalid(3) <= s_axis_ind3_tvalid;
    i_tvalid(4) <= s_axis_ind4_tvalid;
    i_tvalid(5) <= s_axis_ind5_tvalid;
    -- s_axis_ind*_tlast: intentionally unconnected -- two2N has no index tlast port.

    a_tdata(((0+1)*PC_WIDTH)-1 downto 0*PC_WIDTH) <= s_axis_a0_tdata;
    a_tdata(((1+1)*PC_WIDTH)-1 downto 1*PC_WIDTH) <= s_axis_a1_tdata;

    a_tvalid(0) <= s_axis_a0_tvalid;
    a_tvalid(1) <= s_axis_a1_tvalid;

    a_tlast(0)  <= s_axis_a0_tlast;
    a_tlast(1)  <= s_axis_a1_tlast;

    -- slave tkeep is deliberately unused: every beat is a full PC word, so the
    -- engine has no use for byte enables. Reading them would be the only way
    -- this wrapper could acquire logic.

    -- =======================================================================
    -- 2. FAN OUT the bundled tready back to the per-channel slave ports.
    -- =======================================================================
    s_axis_w0_tready <= w_tready(0);
    s_axis_w1_tready <= w_tready(1);
    s_axis_w2_tready <= w_tready(2);
    s_axis_w3_tready <= w_tready(3);
    s_axis_w4_tready <= w_tready(4);
    s_axis_w5_tready <= w_tready(5);
    s_axis_w6_tready <= w_tready(6);
    s_axis_w7_tready <= w_tready(7);
    s_axis_w8_tready <= w_tready(8);
    s_axis_w9_tready <= w_tready(9);
    s_axis_w10_tready <= w_tready(10);
    s_axis_w11_tready <= w_tready(11);
    s_axis_w12_tready <= w_tready(12);
    s_axis_w13_tready <= w_tready(13);
    s_axis_w14_tready <= w_tready(14);
    s_axis_w15_tready <= w_tready(15);

    s_axis_ind0_tready <= i_tready(0);
    s_axis_ind1_tready <= i_tready(1);
    s_axis_ind2_tready <= i_tready(2);
    s_axis_ind3_tready <= i_tready(3);
    s_axis_ind4_tready <= i_tready(4);
    s_axis_ind5_tready <= i_tready(5);

    s_axis_a0_tready <= a_tready(0);
    s_axis_a1_tready <= a_tready(1);

    -- =======================================================================
    -- 3. SPLIT the bundled output bus into the 8 master channel(s), and drive
    --    tkeep all-1s (UG1393 requires it; no ragged tails exist here).
    -- =======================================================================
    m_axis_c0_tdata  <= c_tdata(((0+1)*PC_WIDTH)-1 downto 0*PC_WIDTH);
    m_axis_c1_tdata  <= c_tdata(((1+1)*PC_WIDTH)-1 downto 1*PC_WIDTH);
    m_axis_c2_tdata  <= c_tdata(((2+1)*PC_WIDTH)-1 downto 2*PC_WIDTH);
    m_axis_c3_tdata  <= c_tdata(((3+1)*PC_WIDTH)-1 downto 3*PC_WIDTH);
    m_axis_c4_tdata  <= c_tdata(((4+1)*PC_WIDTH)-1 downto 4*PC_WIDTH);
    m_axis_c5_tdata  <= c_tdata(((5+1)*PC_WIDTH)-1 downto 5*PC_WIDTH);
    m_axis_c6_tdata  <= c_tdata(((6+1)*PC_WIDTH)-1 downto 6*PC_WIDTH);
    m_axis_c7_tdata  <= c_tdata(((7+1)*PC_WIDTH)-1 downto 7*PC_WIDTH);

    m_axis_c0_tvalid <= c_tvalid(0);
    m_axis_c1_tvalid <= c_tvalid(1);
    m_axis_c2_tvalid <= c_tvalid(2);
    m_axis_c3_tvalid <= c_tvalid(3);
    m_axis_c4_tvalid <= c_tvalid(4);
    m_axis_c5_tvalid <= c_tvalid(5);
    m_axis_c6_tvalid <= c_tvalid(6);
    m_axis_c7_tvalid <= c_tvalid(7);

    m_axis_c0_tlast  <= c_tlast(0);
    m_axis_c1_tlast  <= c_tlast(1);
    m_axis_c2_tlast  <= c_tlast(2);
    m_axis_c3_tlast  <= c_tlast(3);
    m_axis_c4_tlast  <= c_tlast(4);
    m_axis_c5_tlast  <= c_tlast(5);
    m_axis_c6_tlast  <= c_tlast(6);
    m_axis_c7_tlast  <= c_tlast(7);

    m_axis_c0_tkeep  <= KEEP_ALL;
    m_axis_c1_tkeep  <= KEEP_ALL;
    m_axis_c2_tkeep  <= KEEP_ALL;
    m_axis_c3_tkeep  <= KEEP_ALL;
    m_axis_c4_tkeep  <= KEEP_ALL;
    m_axis_c5_tkeep  <= KEEP_ALL;
    m_axis_c6_tkeep  <= KEEP_ALL;
    m_axis_c7_tkeep  <= KEEP_ALL;

    c_tready(0) <= m_axis_c0_tready;
    c_tready(1) <= m_axis_c1_tready;
    c_tready(2) <= m_axis_c2_tready;
    c_tready(3) <= m_axis_c3_tready;
    c_tready(4) <= m_axis_c4_tready;
    c_tready(5) <= m_axis_c5_tready;
    c_tready(6) <= m_axis_c6_tready;
    c_tready(7) <= m_axis_c7_tready;

    -- =======================================================================
    -- 4. The verified engine, untouched.
    -- =======================================================================
    DUT : entity work.two2N
        generic map (
            EL_SIZE    => EL_SIZE,
            W_IDX      => W_IDX,
            A_IDX      => A_IDX,
            IND_NUM    => IND_NUM,
            BLOCKS_NUM => BLOCKS_NUM,
            CORES_NUM  => CORES_NUM,
            PC_WIDTH   => PC_WIDTH,
            W_PCS      => W_PCS,
            A_PCS      => A_PCS,
            IND_PCS    => IND_PCS,
            C_PCS      => C_PCS,
            IND_BITS   => IND_BITS
        )
        port map (
            clk               => ap_clk,
            resetn            => ap_rst_n,

            s_axis_w_tdata    => w_tdata,
            s_axis_w_tvalid   => w_tvalid,
            s_axis_w_tready   => w_tready,
            s_axis_w_tlast    => w_tlast,

            s_axis_ind_tdata  => i_tdata,
            s_axis_ind_tvalid => i_tvalid,
            s_axis_ind_tready => i_tready,

            s_axis_a_tdata    => a_tdata,
            s_axis_a_tvalid   => a_tvalid,
            s_axis_a_tlast    => a_tlast,
            s_axis_a_tready   => a_tready,

            m_axis_c_tdata    => c_tdata,
            m_axis_c_tvalid   => c_tvalid,
            m_axis_c_tlast    => c_tlast,
            m_axis_c_tready   => c_tready
        );

end architecture rewire;
